### ISSUE TITLE
Runtime View

### ISSUE THREAD

**Issue by uo281956** [Arquisoft/lomap_es4c#11]
Añadir punto 6 a la documentación

**Comment by uo281956** [comment]
Hacemos un caso de uso cada uno:
- Añadir un punto (Mario)
- Iniciar sesión (Raúl)
- Cargar mapa (Iván)
- Elminar amigo (Pelayo)
- Añadir amigo (Alba)

**Comment by uo281956** [comment]
Añadir información en profundidad. Añadir esquema de varias capas del desarrollo

**Comment by UO282394** [comment]
añadido
