### ISSUE TITLE
Error con los accesos a los botones popup de los puntos

### ISSUE THREAD

**Issue by Raul-Alv** [Arquisoft/lomap_es4c#71]
Al cargar los puntos de los amigos, se llama a la función que cargaría los tres botones a hacer operaciones.

El error está al llamar a la funcion markerFuncs, que busca una imagen para asignar un popup, la cual no existe.

Posibles soluciones:
* Añadir todos los botones, pero hacerlos hidden
* No dejar ningun boton en los puntos de los amigos

**Comment by uo281956** [comment]
Yo quitaria todos los botones y no llamar a la funcion
